<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('categories')->insert([
            ['productid' => 35, 'category' => 'engagement', 'id' => 1],
            ['productid' => 8, 'category' => 'precious_stone', 'id' => 2],
            ['productid' => 16, 'category' => 'engagement', 'id' => 3],
            ['productid' => 33, 'category' => 'engagement', 'id' => 4],
            ['productid' => 33, 'category' => 'precious_stone', 'id' => 5],
            ['productid' => 12, 'category' => 'engagement', 'id' => 6],
            ['productid' => 11, 'category' => 'engagement', 'id' => 7],
            ['productid' => 15, 'category' => 'engagement', 'id' => 8],
            ['productid' => 36, 'category' => 'engagement', 'id' => 10],
            ['productid' => 37, 'category' => 'precious_stone', 'id' => 11],
            ['productid' => 29, 'category' => 'accessories', 'id' => 12],
            ['productid' => 28, 'category' => 'accessories', 'id' => 13],
            ['productid' => 9, 'category' => 'engagement', 'id' => 14],
            ['productid' => 26, 'category' => 'watches', 'id' => 15],
            ['productid' => 18, 'category' => 'art_of_gift', 'id' => 16],
            ['productid' => 38, 'category' => 'engagement', 'id' => 17],
            ['productid' => 10, 'category' => 'engagement', 'id' => 18],
            ['productid' => 17, 'category' => 'art_of_gift', 'id' => 19],
            ['productid' => 6, 'category' => 'engagement', 'id' => 20],
            ['productid' => 23, 'category' => 'watches', 'id' => 21],
            ['productid' => 19, 'category' => 'art_of_gift', 'id' => 22],
            ['productid' => 1, 'category' => 'diamonds', 'id' => 23],
            ['productid' => 13, 'category' => 'precious_stone', 'id' => 25],
            ['productid' => 20, 'category' => 'art_of_gift', 'id' => 26],
            ['productid' => 36, 'category' => 'precious_stone', 'id' => 27],
            ['productid' => 32, 'category' => 'accessories', 'id' => 28],
            ['productid' => 35, 'category' => 'precious_stone', 'id' => 29],
            ['productid' => 12, 'category' => 'precious_stone', 'id' => 30],
            ['productid' => 31, 'category' => 'accessories', 'id' => 31],
            ['productid' => 15, 'category' => 'diamonds', 'id' => 32],
            ['productid' => 34, 'category' => 'precious_stone', 'id' => 33],
            ['productid' => 2, 'category' => 'engagement', 'id' => 34],
            ['productid' => 37, 'category' => 'engagement', 'id' => 35],
            ['productid' => 1, 'category' => 'engagement', 'id' => 36],
            ['productid' => 27, 'category' => 'diamonds', 'id' => 37],
            ['productid' => 4, 'category' => 'engagement', 'id' => 38],
            ['productid' => 34, 'category' => 'engagement', 'id' => 39],
            ['productid' => 13, 'category' => 'engagement', 'id' => 40],
            ['productid' => 7, 'category' => 'engagement', 'id' => 41],
            ['productid' => 3, 'category' => 'engagement', 'id' => 42],
            ['productid' => 25, 'category' => 'watches', 'id' => 43],
            ['productid' => 14, 'category' => 'engagement', 'id' => 44],
            ['productid' => 38, 'category' => 'precious_stone', 'id' => 45],
            ['productid' => 9, 'category' => 'precious_stone', 'id' => 46],
            ['productid' => 5, 'category' => 'engagement', 'id' => 47],
            ['productid' => 10, 'category' => 'diamonds', 'id' => 48],
            ['productid' => 24, 'category' => 'watches', 'id' => 50],
            ['productid' => 30, 'category' => 'accessories', 'id' => 51],
            ['productid' => 38, 'category' => 'diamonds', 'id' => 52],
            ['productid' => 11, 'category' => 'precious_stone', 'id' => 53],
            ['productid' => 16, 'category' => 'diamonds', 'id' => 54],
            ['productid' => 37, 'category' => 'diamonds', 'id' => 55],
            ['productid' => 41, 'category' => 'diamonds', 'id' => 57],
            ['productid' => 40, 'category' => 'accessories', 'id' => 58],
            ['productid' => 41, 'category' => 'accessories', 'id' => 59],
            ['productid' => 39, 'category' => 'accessories', 'id' => 60],
            ['productid' => 1, 'category' => 'ring', 'id' => 61],
            ['productid' => 2, 'category' => 'ring', 'id' => 62],
            ['productid' => 3, 'category' => 'ring', 'id' => 63],
            ['productid' => 4, 'category' => 'ring', 'id' => 64],
            ['productid' => 5, 'category' => 'ring', 'id' => 65],
            ['productid' => 6, 'category' => 'ring', 'id' => 66],
            ['productid' => 3, 'category' => 'diamonds', 'id' => 67],
            ['productid' => 7, 'category' => 'ring', 'id' => 68],
            ['productid' => 8, 'category' => 'ring', 'id' => 69],
            ['productid' => 9, 'category' => 'ring', 'id' => 70],
            ['productid' => 10, 'category' => 'ring', 'id' => 71],
            ['productid' => 11, 'category' => 'ring', 'id' => 72],
            ['productid' => 12, 'category' => 'ring', 'id' => 73],
            ['productid' => 13, 'category' => 'ring', 'id' => 74],
            ['productid' => 14, 'category' => 'ring', 'id' => 75],
            ['productid' => 15, 'category' => 'ring', 'id' => 76],
            ['productid' => 16, 'category' => 'ring', 'id' => 77],
            ['productid' => 17, 'category' => 'gift', 'id' => 78],
            ['productid' => 20, 'category' => 'gift', 'id' => 81],
            ['productid' => 23, 'category' => 'accessory', 'id' => 82],
            ['productid' => 24, 'category' => 'accessory', 'id' => 83],
            ['productid' => 25, 'category' => 'accessory', 'id' => 84],
            ['productid' => 26, 'category' => 'accessory', 'id' => 85],
            ['productid' => 27, 'category' => 'earring', 'id' => 86],
            ['productid' => 39, 'category' => 'earring', 'id' => 87],
            ['productid' => 40, 'category' => 'earring', 'id' => 88],
            ['productid' => 28, 'category' => 'accessory', 'id' => 89],
            ['productid' => 29, 'category' => 'accessory', 'id' => 90],
            ['productid' => 30, 'category' => 'necklace', 'id' => 91],
            ['productid' => 31, 'category' => 'necklace', 'id' => 92],
            ['productid' => 32, 'category' => 'necklace', 'id' => 93],
            ['productid' => 33, 'category' => 'ring', 'id' => 94],
            ['productid' => 34, 'category' => 'ring', 'id' => 95],
            ['productid' => 36, 'category' => 'ring', 'id' => 97],
            ['productid' => 37, 'category' => 'ring', 'id' => 98],
            ['productid' => 38, 'category' => 'ring', 'id' => 99],
            ['productid' => 41, 'category' => 'earring', 'id' => 100],
            ['productid' => 42, 'category' => 'art_of_gift', 'id' => 107],
            ['productid' => 21, 'category' => 'watches', 'id' => 130],
            ['productid' => 21, 'category' => 'accessory', 'id' => 133],
            ['productid' => 19, 'category' => 'gift', 'id' => 139],
            ['productid' => 42, 'category' => 'ring', 'id' => 140],
        ]);
    }
}