<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 21,
                'productname' => 'YELLOW GOLD WATCH',
                'productdesc' => '18ct gold alloy unisex watch',
                'price' => 5599,
                'imagename' => 'watch1.png',
                'imagename2' => 'watch1.1.png',
                'imagename3' => 'watch2.2.png',
                'imagename4' => 'watch2.3.png',
                'type' => 'Yellow Gold',
                'paving' => true,
            ],
            [
                'id' => 36,
                'productname' => 'PLATINUM SAPPHIRE RING',
                'productdesc' => '4-carat sapphire ring set in platinum with engraving in platinum.',
                'price' => 3599.99,
                'imagename' => 'ring15.png',
                'imagename2' => 'ring15.1.png',
                'imagename3' => 'ring15.2.png',
                'imagename4' => 'ring15.2.png',
                'type' => 'Platinum',
                'paving' => false,
            ],
            [
                'id' => 9,
                'productname' => 'SAPPHIRE WHITE GOLD RING WITH DIAMONDS',
                'productdesc' => '4-carat sapphire ring with 20 0.5-carat diamonds in white gold with engraving',
                'price' => 1723.23,
                'imagename' => 'ring7.png',
                'imagename2' => 'ring7.1.png',
                'imagename3' => 'ring7.2.png',
                'imagename4' => 'ring7.3.png',
                'type' => 'White gold',
                'paving' => true,
            ],
            [
                'id' => 14,
                'productname' => 'SAPPHIRE PLATINUM RING',
                'productdesc' => 'Sapphire ring in platinum with engraving',
                'price' => 2250.99,
                'imagename' => 'ring12.png',
                'imagename2' => 'ring12.1.png',
                'imagename3' => 'ring7.2.png',
                'imagename4' => 'ring7.3.png',
                'type' => 'Platinum',
                'paving' => false,
            ],
            [
                'id' => 16,
                'productname' => 'DIAMOND RING',
                'productdesc' => '3-carat diamond ring with in platinum',
                'price' => 1982.9,
                'imagename' => 'diamondring4.png',
                'imagename2' => 'diamondring4.1.png',
                'imagename3' => 'diamondring2.2.png',
                'imagename4' => 'diamondring2.3.png',
                'type' => 'Platinum',
                'paving' => false,
            ],
            [
                'id' => 6,
                'productname' => 'ROSE GOLD RING',
                'productdesc' => 'Ring in 585 rose gold',
                'price' => 725.7,
                'imagename' => 'ring4.png',
                'imagename2' => 'ring4.1.png',
                'imagename3' => 'ring2.3.png',
                'imagename4' => 'ring2.4.png',
                'type' => 'Rose Gold',
                'paving' => false,
            ],
            [
                'id' => 10,
                'productname' => 'DIAMOND RING',
                'productdesc' => '1-carat diamond ring in platinum',
                'price' => 850.2,
                'imagename' => 'ring8.png',
                'imagename2' => 'ring8.1.png',
                'imagename3' => 'ring8.2.png',
                'imagename4' => 'ring8.3.png',
                'type' => 'Platinum',
                'paving' => false,
            ],
            [
                'id' => 13,
                'productname' => 'EMERALD YELLOW GOLD RING',
                'productdesc' => '3.5-carat emerald ring in 585 rose gold',
                'price' => 2130.1,
                'imagename' => 'ring10.png',
                'imagename2' => 'ring10.1.png',
                'imagename3' => 'ring10.2.png',
                'imagename4' => 'ring10.3.png',
                'type' => 'Rose Gold',
                'paving' => false,
            ],
            [
                'id' => 41,
                'productname' => 'YELLOW GOLD DIAMOND DEARRINGS',
                'productdesc' => '1-carat diamond stud earrings in yellow gold',
                'price' => 6534.9,
                'imagename' => 'earring2.png',
                'imagename2' => 'earring2.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 17,
                'productname' => 'COFFEE MUG IN GREY LOGO COLOUR',
                'productdesc' => 'Coffee mug with our logo. Simple',
                'price' => 24.99,
                'imagename' => 'gift1.png',
                'imagename2' => 'gift1.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Other',
                'paving' => false,
            ],
            [
                'id' => 18,
                'productname' => 'COFFEE MUG IN ICONIC LOGO COLOUR',
                'productdesc' => 'Coffee mug with our logo. Simple',
                'price' => 24.99,
                'imagename' => 'gift3.png',
                'imagename2' => 'gift3.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Other',
                'paving' => true,
            ],
            [
                'id' => 19,
                'productname' => 'BASEBALL CAP',
                'productdesc' => 'For casual outfit lovers',
                'price' => 30,
                'imagename' => 'gift4.png',
                'imagename2' => 'gift4.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Other',
                'paving' => false,
            ],
            [
                'id' => 37,
                'productname' => 'DIAMOND EMERALD RING',
                'productdesc' => '2-carat emerald with diamond accents in white gold',
                'price' => 3600.99,
                'imagename' => 'ring17.png',
                'imagename2' => 'ring17.1.png',
                'imagename3' => 'ring17.2.png',
                'imagename4' => 'ring17.3.png',
                'type' => 'White gold',
                'paving' => true,
            ],
            [
                'id' => 3,
                'productname' => 'DIAMOND RING',
                'productdesc' => '2.5-carat diamond ring in platinum',
                'price' => 1755.99,
                'imagename' => 'diamondring2.png',
                'imagename2' => 'diamondring2.1.png',
                'imagename3' => 'diamondring2.2.png',
                'imagename4' => 'diamondring2.3.png',
                'type' => 'Platinum',
                'paving' => false,
            ],
            [
                'id' => 38,
                'productname' => 'DIAMOND AQUAMARINE RING',
                'productdesc' => '3-carat aquamarine ring with a diamond halo. White gold',
                'price' => 4600.99,
                'imagename' => 'ring18.png',
                'imagename2' => 'ring18.1.png',
                'imagename3' => 'ring18.2.png',
                'imagename4' => 'ring18.3.png',
                'type' => 'White gold',
                'paving' => true,
            ],
            [
                'id' => 12,
                'productname' => 'EMERALD YELLOW GOLD RING',
                'productdesc' => '3.5-carat emerald ring in 585 yellow gold',
                'price' => 1950.99,
                'imagename' => 'ring11.png',
                'imagename2' => 'ring11.1.png',
                'imagename3' => 'ring10.2.png',
                'imagename4' => 'ring10.3.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 2,
                'productname' => 'YELLOW GOLD RING',
                'productdesc' => 'Ring in 585 yellow gold',
                'price' => 870.99,
                'imagename' => 'ring1.png',
                'imagename2' => 'ring1.1.png',
                'imagename3' => 'ring2.3.png',
                'imagename4' => 'ring2.4.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 7,
                'productname' => 'YELLOW GOLD RING',
                'productdesc' => 'A narrow-cut ring in 585 yellow gold',
                'price' => 645.99,
                'imagename' => 'ring5.png',
                'imagename2' => 'ring5.1.png',
                'imagename3' => 'ring2.3.png',
                'imagename4' => 'ring2.4.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 11,
                'productname' => 'RUBY RING',
                'productdesc' => '1-carat ruby ring in 954 silver',
                'price' => 450.7,
                'imagename' => 'ring9.png',
                'imagename2' => 'ring9.1.png',
                'imagename3' => 'ring8.2.png',
                'imagename4' => 'ring8.3.png',
                'type' => 'Silver',
                'paving' => false,
            ],
            [
                'id' => 25,
                'productname' => 'STAINLESS STEEL WATCH',
                'productdesc' => 'Stainless steel watch in a modern design',
                'price' => 3255.75,
                'imagename' => 'watch5.png',
                'imagename2' => 'watch5.1.png',
                'imagename3' => 'watch6.2.png',
                'imagename4' => 'watch6.3.png',
                'type' => 'Stainless steel',
                'paving' => false,
            ],
            [
                'id' => 24,
                'productname' => 'DIAMOND WATCH',
                'productdesc' => 'Diamond watch in stainless steel',
                'price' => 9999.99,
                'imagename' => 'watch4.png',
                'imagename2' => 'watch4.1.png',
                'imagename3' => 'watch6.2.png',
                'imagename4' => 'watch6.3.png',
                'type' => 'Stainless steel',
                'paving' => true,
            ],
            [
                'id' => 29,
                'productname' => 'SILK SCARF',
                'productdesc' => 'Silk scarf that could be worn as a bandana or a bag accessory',
                'price' => 450,
                'imagename' => 'accessories2.png',
                'imagename2' => 'accessories2.1.png',
                'imagename3' => 'accessories_woman.png',
                'imagename4' => 'accessories2.png',
                'type' => 'Other',
                'paving' => false,
            ],
            [
                'id' => 40,
                'productname' => 'YELLOW GOLD EARRINGS WITH ENGRAVING',
                'productdesc' => 'Yellow gold stud earrings with flower motif engraving.',
                'price' => 1235,
                'imagename' => 'earring1.png',
                'imagename2' => 'earring1.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 28,
                'productname' => 'SUNGLASSES',
                'productdesc' => 'Stylish gold unisex sunglasses',
                'price' => 120,
                'imagename' => 'accessories1.png',
                'imagename2' => 'accessories1.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Other',
                'paving' => false,
            ],
            [
                'id' => 30,
                'productname' => 'SILVER NECKLACE',
                'productdesc' => 'Necklace in 945 silver',
                'price' => 459.8,
                'imagename' => 'necklace1.png',
                'imagename2' => 'necklace1.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Silver',
                'paving' => false,
            ],
            [
                'id' => 20,
                'productname' => 'JEWELLERY STORE BOOK',
                'productdesc' => 'Book about out store and its traditions',
                'price' => 54.99,
                'imagename' => 'gift5.png',
                'imagename2' => 'gift5.1.png',
                'imagename3' => 'gift5.2.png',
                'imagename4' => 'img.png',
                'type' => 'Other',
                'paving' => false,
            ],
            [
                'id' => 31,
                'productname' => 'YELLOW GOLD NECKLACE',
                'productdesc' => 'Necklace in yellow 584 gold',
                'price' => 649.99,
                'imagename' => 'necklace2.png',
                'imagename2' => 'necklace2.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 39,
                'productname' => 'YELLOW GOLD EARRINGS',
                'productdesc' => 'Classic-style yellow gold earrings.',
                'price' => 5399.99,
                'imagename' => 'earing4.png',
                'imagename2' => 'earing4.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 8,
                'productname' => 'YELLOW GOLD CITRINE RING',
                'productdesc' => '3.5-carat citrine ring in 585 yellow gold',
                'price' => 1678.87,
                'imagename' => 'ring6.png',
                'imagename2' => 'ring6.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 1,
                'productname' => 'DIAMOND RING',
                'productdesc' => '2-carat diamond ring with 10 0.5-carat diamonds in white gold',
                'price' => 1500.99,
                'imagename' => 'diamondring1.png',
                'imagename2' => 'diamondring1.1.png',
                'imagename3' => 'diamondring1.2.png',
                'imagename4' => 'diamondring1.3.png',
                'type' => 'White gold',
                'paving' => true,
            ],
            [
                'id' => 27,
                'productname' => 'DIAMOND EARRINGS',
                'productdesc' => 'Diamond earrings in white gold',
                'price' => 4302.3,
                'imagename' => 'earing3.png',
                'imagename2' => 'earring3.1.png',
                'imagename3' => 'earring3.2.png',
                'imagename4' => 'earring3.3.png',
                'type' => 'White gold',
                'paving' => true,
            ],
            [
                'id' => 33,
                'productname' => 'GOLDEN RUBY RING',
                'productdesc' => '1-carat ruby ring in yellow gold with a round ruby set in a simple, polished band.',
                'price' => 850.2,
                'imagename' => 'ring13.png',
                'imagename2' => 'ring13.1.png',
                'imagename3' => 'ring13.2.png',
                'imagename4' => 'ring13.3.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 15,
                'productname' => 'DIAMOND RING',
                'productdesc' => '3-carat diamond ring with in white gold',
                'price' => 1980.9,
                'imagename' => 'diamondring3.png',
                'imagename2' => 'diamondring3.1.png',
                'imagename3' => 'diamondring2.2.png',
                'imagename4' => 'diamondring2.3.png',
                'type' => 'White gold',
                'paving' => false,
            ],
            [
                'id' => 34,
                'productname' => 'GOLDEN AMETYST RING',
                'productdesc' => '1-carat amethyst ring in 585 yellow gold.',
                'price' => 649.99,
                'imagename' => 'ring14.png',
                'imagename2' => 'ring14.1.png',
                'imagename3' => 'ring14.2.png',
                'imagename4' => 'ring14.3.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 4,
                'productname' => 'YELLOW GOLD RING',
                'productdesc' => 'Ring in 585 yellow gold with engraving',
                'price' => 750.8,
                'imagename' => 'ring2.png',
                'imagename2' => 'ring2.1.png',
                'imagename3' => 'ring2.3.png',
                'imagename4' => 'ring2.4.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 26,
                'productname' => 'STAINLESS STEEL WATCH',
                'productdesc' => 'Stainless steel watch in a classical design',
                'price' => 3265.75,
                'imagename' => 'watch6.png',
                'imagename2' => 'watch6.1.png',
                'imagename3' => 'watch6.2.png',
                'imagename4' => 'watch6.3.png',
                'type' => 'Stainless steel',
                'paving' => false,
            ],
            [
                'id' => 23,
                'productname' => 'PURE DIAMOND WATCH',
                'productdesc' => 'Pure diamond watch in platinum and stainless steel. Special order for special clients',
                'price' => 10000.99,
                'imagename' => 'watch3.png',
                'imagename2' => 'watch3.1.png',
                'imagename3' => 'watch6.2.png',
                'imagename4' => 'watch6.3.png',
                'type' => 'Platinum',
                'paving' => true,
            ],
            [
                'id' => 5,
                'productname' => 'SILVER RING',
                'productdesc' => 'Silver 945 ring',
                'price' => 350.66,
                'imagename' => 'ring3.png',
                'imagename2' => 'ring3.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Silver',
                'paving' => false,
            ],
            [
                'id' => 32,
                'productname' => 'YELLOW GOLD NECKLACE',
                'productdesc' => 'Flower motif necklace in yellow 584 gold',
                'price' => 679.99,
                'imagename' => 'necklace3.png',
                'imagename2' => 'necklace3.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Yellow Gold',
                'paving' => false,
            ],
            [
                'id' => 35,
                'productname' => 'SILVER AMETYST RING',
                'productdesc' => '1.5-carat triangular amethyst set in a polished silver band.',
                'price' => 750.99,
                'imagename' => 'ring16.png',
                'imagename2' => 'ring16.1.png',
                'imagename3' => 'img.png',
                'imagename4' => 'img.png',
                'type' => 'Silver',
                'paving' => false,
            ],
            [
                'id' => 42,
                'productname' => 'Test product',
                'productdesc' => 'Test Product was created for the testing of adding the products from adminpage \'a_addproduct\' :O',
                'price' => 1000,
                'imagename' => 'test-product_mFzIY.jpg',
                'imagename2' => 'test-product_kQ68l.png',
                'imagename3' => 'test-product_rml3y.png',
                'imagename4' => 'test-product_jIT9v.png',
                'type' => 'Other',
                'paving' => false,
            ],
        ]);
    }
}
